### ISSUE TITLE
Classic user problem: private libraries

### ISSUE THREAD

**Issue by ehenneken** [adsabs/Team#10]
From: Sergio Cellone
Address: turnos@casleo.gov.ar

Comments:
I need your help, please. I had a personal account (scellone@fcaglp.unlp.edu.ar) and an institutional account (turnos@casleo.gov.ar). When trying to import my private libraries to the ADS Bumblebee, I somehow made a mistake, and now my libraries from the personal account are in the institutional account, while those formerly in the institutional account have vanished.

**Comment by aaccomazzi** [comment]
The issue is related with how things are reverse-proxied.  This works (from adsx):
```
curl 'http://54.226.236.143/cgi-bin/maint/export_privlib?cookie=460b999f39'
```
but this doesn't:
```
curl 'http://adsabs.harvard.edu/cgi-bin/maint/export_privlib?cookie=460b999f39'
```
