### ISSUE TITLE
Do single token simbid cause problems

### ISSUE THREAD

**Issue by spacemansteve** [adsabs/Team#110]
Nearly every simbad ids has two tokens (1471036 SB*), but not all (1508007).  If we create parallel arrays for Solr with numeric and text fields, does this cause an alignment problem?  Should the  include single token simbad ids be sent to Solr?  

This issue is for fact-finding.  Once understood, a development issue in the appropriate repo should be created.

http://simbad.u-strasbg.fr/simbad/sim-id?Ident=%401508007&Name=TYC%202214-1198-1#lab_ident

**Comment by ehenneken** [comment]
There seems to be a bug on the SIMBAD side. There always should be a "object type" (third column). The SIMBAD identifier (2nd column) is *always* an integer.

**Comment by ehenneken** [comment]
Anaïs Oberto (SIMBAD) wrote back that those entries in `simbad_objects.tab` with a missing entry in the third column (i.e. no object type) are indeed incorrect. They claim to have solved the problem and I will verify this as part of

**Comment by ehenneken** [comment]
The problem has been partially resolved... I reran our SIMBAD harvesting procedure manually and checked for the example `2016PASP..128h2001H`. Entries that first did not have an object type, now have object type `HS*`. However, there are still entries with no object type (see e.g. `2003A&A...411..361K`). Those seem to correspond with a value of '~' on the SIMBAD UI, but that is not returned from the database.
