### ISSUE TITLE
metrics database  - checks

### ISSUE THREAD

**Issue by ehenneken** [adsabs/Team#166]
Before going live with the new pipeline, there are two important checks

1. After a full ingest, are there any records missing in the database corresponding with canonical bibcodes? If so, which and why. (this should not happen)
2. Suppose some of the ADS Classic column files are not created properly, are there measures in place to skip the update of the RDS metrics database? Stale data is better than incorrect data.

**Comment by spacemansteve** [comment]
The following bibcode are in the canonical list but do not have an entry in the test metrics database.

[https://app.zenhub.com/files/106747035/83277af9-d264-4350-827d-9072461b55c0/download](https://app.zenhub.com/files/106747035/83277af9-d264-4350-827d-9072461b55c0/download)
