### ISSUE TITLE
bitmap mirroring for phae.proj

### ISSUE THREAD

**Issue by ehenneken** [adsabs/Team#60]
The bitmaps for phae.proj are not mirrored automatically

**Comment by ehenneken** [comment]
@aaccomazzi is there something in the ADS Perl modules where publication types are hardcoded? I'm wondering whether these bitmaps don't get mirrored because the publication type `proj` is not recognized.

**Comment by aaccomazzi** [comment]
As discussed, the script `/proj/ads/soft/articles/bin/artlists` uses the list of publication types specified in `/proj/ads/articles/bitmaps/pubtypes.list` to generate the list of volumes to be mirrored.
